navikt/tjenestespesifikasjoner

dokumentforsendelse-v1-meldingsdefinisjon/src/main/xsd/no/nav/melding/virksomhet/dokumentforsendelse/v1/xsd/dokumentforsendelse.xsd
[SD-235] Oppdaterer dokumentforsendelse xsd-en etter endringer i DOKMOT grensesnittet.
=> Utvidelse av dokumentforsendelse

nav-innsynJournal-v2-tjenestespesifikasjon/pom.xml, nav-innsynJournal-v2-tjenestespesifikasjon/src/main/assembly/zip-assembly.xml, nav-innsynJournal-v2-tjenestespesifikasjon/src/main/resources/innsynJournal.xjb, nav-innsynJournal-v2-tjenestespesifikasjon/src/main/resources/wsdl/no/nav/tjeneste/virksomhet/innsynJournal/v2/Binding.wsdl, nav-innsynJournal-v2-tjenestespesifikasjon/src/main/resources/wsdl/no/nav/tjeneste/virksomhet/innsynJournal/v2/feil/feil.xsd, nav-innsynJournal-v2-tjenestespesifikasjon/src/main/resources/wsdl/no/nav/tjeneste/virksomhet/innsynJournal/v2/informasjon/informasjon.xsd, nav-innsynJournal-v2-tjenestespesifikasjon/src/main/resources/wsdl/no/nav/tjeneste/virksomhet/innsynJournal/v2/innsynJournal.wsdl, nav-innsynJournal-v2-tjenestespesifikasjon/src/main/resources/wsdl/no/nav/tjeneste/virksomhet/innsynJournal/v2/meldinger/meldinger.xsd
Fint om du bare sjekker over at jeg har gjort alt rett.
=> Lagt til ny tjenestespesifikasjon for innsyn

nav-virksomhet-paaloepteUtgifter-v1-meldingsdefinisjon/pom.xml, nav-virksomhet-paaloepteUtgifter-v1-meldingsdefinisjon/src/main/xsd/paaloepteUtgifter.xsd, nav-virksomhet-soeknadsskjema-v1-meldingsdefinisjon/pom.xml, nav-virksomhet-soeknadsskjema-v1-meldingsdefinisjon/src/main/xsd/soeknadsskjema.xsd
=> Legg til paaloepteUtgifter og soeknadsskjema

.travis.yml
This reverts commit f201b19d9c19e4966a77477eafeeeb4ffcdfe344.
=> Revert "Get more log output from maven when releasing"

nav-virksomhet-dokumentnotifikasjon-v1-meldingsdefinisjon/pom.xml
Forrige PR som ble merget til master feilet i Travis selv om koden bygde successful. Har laget ny PR for å se om bygget går igjennom ok i Travis.
=> Dokumentnotifikasjon: Setter samme version som i hoved pom

digisyfo-sykepengesoeknadarbeidsgiver/pom.xml, pom.xml
=> Legger til sykepengesoeknadarbeidsgiver som modul i parent pom

juridisk-logg/pom.xml, juridisk-logg/src/main/wsdl/archiver.xsd, juridisk-logg/src/main/wsdl/ws-addr.xsd
Tar inn oppdatert versjon av grensesnittet til emottak
=> Juridisklogg

sykefravaersoppfoelgingv1-tjenestespesifikasjon/src/main/wsdl/no/nav/tjeneste/virksomhet/sykefravaersoppfoelging/v1/Binding.wsdl, sykefravaersoppfoelgingv1-tjenestespesifikasjon/src/main/wsdl/no/nav/tjeneste/virksomhet/sykefravaersoppfoelging/v1/informasjon/informasjon.xsd, sykefravaersoppfoelgingv1-tjenestespesifikasjon/src/main/wsdl/no/nav/tjeneste/virksomhet/sykefravaersoppfoelging/v1/meldinger/meldinger.xsd, sykefravaersoppfoelgingv1-tjenestespesifikasjon/src/main/wsdl/no/nav/tjeneste/virksomhet/sykefravaersoppfoelging/v1/sykefravaersoppfoelging.wsdl, sykefravaersoppfoelgingv1-tjenestespesifikasjon/src/main/wsdl/sykefravaersoppfoelgingv1/bindings.xml
Sykefravaersoppfoelgingv1-tjenestespesifikasjon er ikke oppdatert, så har hentet inn xml/xsd/wsdl hentes in fra
https://stash.adeo.no/projects/SYFO/repos/syfotjenester/browse/sykefravaersoppfoelgingv1.
=> Oppgrader sykefravaersoppfoelgingv1-tjenestespesifikasjon

udi-personstatus-v1/pom.xml, udi-personstatus-v1/src/main/wsdl/bindings.xml
legge til bindingsparamter for aa få det til fungerer som gosys i VDI
=> Endre bindingfil for å få gosys fungere med GPR.

pensjonsinformasjon-v1-tjenestespesifikasjon/src/main/resources/pensjonsinformasjon/v1/v1.Vedtak.xsd
team eessi trenger vedtaksdato ved uthenting av pensjonsinformasjon
=> pl-1060: oppdatering av vedstaks dato

nav-fim-behandlejournal-v3-tjenestespesifikasjon/pom.xml
Co-authored-by: Mo Amini <mo.amini@nav.no>
=> Endrer behandleJournal tilbake til opprinnelig

nav-fim-echo-tjenestespesifikasjon/pom.xml
Co-authored-by: Mo Amini <mo.amini@nav.no>
=> Diverse WSDL til lowercase

nav-fim-person-v1-tjenestespesifikasjon/pom.xml, nav-fim-virgo-v1-tjenestespesifikasjon/pom.xml
Co-authored-by: Mo Amini <mo.amini@nav.no>
=> Diverse WSDL til lowercase nav-fim-tjenestespesifikasjon

infotrygd-vedtak/.gitattributes, infotrygd-vedtak/.gitignore, infotrygd-vedtak/pom.xml, infotrygd-vedtak/src/main/wsdl/no/nav/tjeneste/virksomhet/infotrygdvedtak/v1/Binding.wsdl, infotrygd-vedtak/src/main/wsdl/no/nav/tjeneste/virksomhet/infotrygdvedtak/v1/feil/feil.xsd, infotrygd-vedtak/src/main/wsdl/no/nav/tjeneste/virksomhet/infotrygdvedtak/v1/informasjon/informasjon.xsd, infotrygd-vedtak/src/main/wsdl/no/nav/tjeneste/virksomhet/infotrygdvedtak/v1/infotrygdVedtak.wsdl, infotrygd-vedtak/src/main/wsdl/no/nav/tjeneste/virksomhet/infotrygdvedtak/v1/meldinger/meldinger.xsd, pom.xml
Enslig forsørger i team familie skal kalle på denne tjenesten i en periode for å verifisere att man får lik data som fra infotrygd replika
Litt usikker på hvem som har ansvaret å sjekke PR's her. 
https://confluence.adeo.no/display/ARENA/Arena+-+Tjenestekonsument+Webservice+-+Infotrygd+InfotrygdVedtak_v1#
=> Lagt til klient for å kalle på infotrygd vedtak

nav-virksomhet-soeknadsskjema-v1-meldingsdefinisjon/src/main/xsd/soeknadsskjema.xsd
Skjema er oppdatert i forhold til det vi diskuterte her : https://nav-it.slack.com/archives/C023JL6SM4N/p1622629763009300?thread_ts=1622622508.001300&cid=C023JL6SM4N
=> Update soeknadsskjema med maanedligUtgiftTilsynBarn felt

henvendelse-soknader-tjenestespesifikasjon/pom.xml
DAG-144
Co-authored-by: Jørn Greger Nyegaard-Larsen <jorn.greger.nyegaard-larsen@nav.no>
Co-authored-by: Celine Dam <celine.ten.dam@nav.no>
=> Inkludere WSDL mappe i pakke som alle andre tjenestespesifikasjoner

arena-organisasjon-tjenestespesifikasjon/src/main/wsdl/ArenaOrganisasjonService.wsdl
- Fjernet overflødig whitespace for å trigge ny release.
=> Lagt inn WSDL for ArenaOrganisasjonService - retry release

utbetalingstransaksjon-v1-meldingsdefinisjon/src/main/xsd/no/nav/melding/virksomhet/utbetalingstransaksjon/v1/utbetalingstransaksjon.xsd
- Lagt til utbetalesEtter-felt i utbetalingstransaksjon-meldingen.
=> Utvidelse av utbetalingstransaksjon-meldingen

feilutbetalingsvedtak-v1-meldingsdefinisjon/src/main/xsd/no/nav/melding/virksomhet/feilutbetalingsvedtak/v1/feilutbetalingsvedtak.xsd
- Lagt til foreldetForDato-felt i feilutbetalingsvedtak-meldingen.
=> Utvidelse av feilutbetalingsvedtak med foreldetForDato

feilutbetalingsvedtak-v1-meldingsdefinisjon/src/main/xsd/no/nav/melding/virksomhet/feilutbetalingsvedtak/v1/feilutbetalingsvedtak.xsd
- Lagt til grunnlagsbelopSkylddeling-felt i feilutbetalingsvedtak-meldingen.
=> Utvidelse av feilutbetalingsvedtak med grunnlagsbelopSkylddeling

feilutbetalingsvedtakavstemming-v1-meldingsdefinisjon/pom.xml, feilutbetalingsvedtakavstemming-v1-meldingsdefinisjon/src/main/xsd/no/nav/melding/virksomhet/feilutbetalingsvedtakavstemming/v1/feilutbetalingsvedtakavstemming.xsd, pom.xml
- Nytt meldingsgrensesnitt for feilutbetalingsvedtakavstemming.
=> Add feilutbetalingsvedtakavstemming v1 meldingsdefinisjon

nav-virksomhet-oppdragsbehandling-v1-meldingsdefinisjon/src/main/xsd/no/trygdeetaten/skjema/oppdrag/oppdragskjema-1.xsd
=> Lagt til Avvent-118 i oppdrag-110

arena-vedtakhendelser/src/main/xsd/vedtakHendelser.xsd
- Lagt til ikke-påkrevd fodelsnr-felt i arena-vedtakshendelser.
- Endret aktoerID til ikke-påkrevd.
=> Utvidet arena-vedtakshendelser med fodselsnr-felt

nav-system-os-simuler-fp-service-tjenestespesifikasjon/src/main/wsdl/no/nav/system/os/entiteter/oppdragSkjema.xsd, nav-system-os-simuler-fp-service-tjenestespesifikasjon/src/main/wsdl/no/nav/system/os/tjenester/simulerFpService/simulerFpServiceServiceTypes.xsd, nav-virksomhet-oppdragsbehandling-v1-meldingsdefinisjon/src/main/xsd/no/trygdeetaten/skjema/oppdrag/oppdragskjema-1.xsd
https://jira.adeo.no/browse/TOB-4415
=> TOB-4415 - oppdater oppdrag simulering med ID157 og ID118
